@host = http://localhost:8001

###

GET {{host}}/health HTTP/1.1
Accept: application/json

###

# @name submit_task
POST {{host}}/api/run HTTP/1.1
Content-Type: application/json

{
    "task": "Implement web app project that will visualize the events trace for the agentflow runs, examples of the runs can be found in the agentflow workspace/run folder, the app should be able to display the events in a timeline view, and allow filtering by event type and time range.",
    "context": {
        "language": "Typescript",
        "tooling": "vite",
        "framework": "react",
        "type": "web, spa"
    },
    "budget_usd": 5.0
}

###

# {
#     "task": "Create a simple REST API using FastAPI that returns a greeting message.",
#     "context": {
#         "language": "Python",
#         "framework": "FastAPI",
#         "response_format": "JSON",
#         "dependency_management": "uv"
#     }
# }

###

@run_id = {{submit_task.response.body.run_id}}

###

GET {{host}}/api/run/{{run_id}}/stream HTTP/1.1 
Accept: text/event-stream

